export const PLATFORM_PERMISSIONS = {
  ENTITLEMENT_VIEW: "platform.entitlement.view",
  ENTITLEMENT_MANAGE: "platform.entitlement.manage",
  TENANT_PROVISION: "platform.tenant.provision",
  TENANT_MANAGE: "platform.tenant.manage",
  SUPPORT_ACCESS: "platform.support.access",
  VALIDATION_ADMIN: "platform.validation.admin",
  PLATFORM_AUDIT_VIEW: "platform.audit.view",
} as const;

export type PlatformPermission =
  (typeof PLATFORM_PERMISSIONS)[keyof typeof PLATFORM_PERMISSIONS];

export const PLATFORM_ROLES = {
  SUPER_ADMIN: "PLATFORM_SUPER_ADMIN",
  SECURITY_ADMIN: "PLATFORM_SECURITY_ADMIN",
  QA_ADMIN: "PLATFORM_QA_ADMIN",
  SUPPORT: "PLATFORM_SUPPORT",
  AUDITOR: "PLATFORM_AUDITOR",
} as const;

export type PlatformRole = (typeof PLATFORM_ROLES)[keyof typeof PLATFORM_ROLES];

export const PLATFORM_ROLE_PERMISSIONS: Record<
  PlatformRole,
  readonly PlatformPermission[]
> = {
  PLATFORM_SUPER_ADMIN: Object.values(PLATFORM_PERMISSIONS),
  PLATFORM_SECURITY_ADMIN: [
    PLATFORM_PERMISSIONS.ENTITLEMENT_VIEW,
    PLATFORM_PERMISSIONS.ENTITLEMENT_MANAGE,
    PLATFORM_PERMISSIONS.TENANT_MANAGE,
    PLATFORM_PERMISSIONS.SUPPORT_ACCESS,
    PLATFORM_PERMISSIONS.PLATFORM_AUDIT_VIEW,
  ],
  PLATFORM_QA_ADMIN: [
    PLATFORM_PERMISSIONS.ENTITLEMENT_VIEW,
    PLATFORM_PERMISSIONS.VALIDATION_ADMIN,
    PLATFORM_PERMISSIONS.PLATFORM_AUDIT_VIEW,
  ],
  PLATFORM_SUPPORT: [
    PLATFORM_PERMISSIONS.ENTITLEMENT_VIEW,
    PLATFORM_PERMISSIONS.SUPPORT_ACCESS,
  ],
  PLATFORM_AUDITOR: [
    PLATFORM_PERMISSIONS.ENTITLEMENT_VIEW,
    PLATFORM_PERMISSIONS.PLATFORM_AUDIT_VIEW,
  ],
};

export function platformRoleHasPermission(
  roleKey: PlatformRole,
  permission: PlatformPermission,
): boolean {
  return PLATFORM_ROLE_PERMISSIONS[roleKey]?.includes(permission) ?? false;
}
