export const PERMISSIONS = {
  SEARCH_EXECUTE: "literature.search.execute",
  SEARCH_EXPORT: "literature.search.export",
  SEARCH_HISTORY_VIEW: "literature.search.history.view",
  EVIDENCE_CREATE: "literature.evidence.create",
  HITS_SUBMIT: "literature.hits.submit",
  CONFIG_VIEW: "tenant.configuration.view",
  CONFIG_UPLOAD: "tenant.configuration.upload",
  CONFIG_CREATE: "tenant.configuration.create",
  CONFIG_VALIDATE: "tenant.configuration.validate",
  CONFIG_APPROVE: "tenant.configuration.approve",
  CONFIG_ACTIVATE: "tenant.configuration.activate",
  CONFIG_RETIRE: "tenant.configuration.retire",
  SOURCE_MANAGE: "literature.source.manage",
  AUDIT_VIEW: "tenant.configuration.audit.view",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS: Record<string, readonly Permission[]> = {
  CLINIXAI_SUPER_ADMIN: Object.values(PERMISSIONS),
  CLIENT_OWNER: Object.values(PERMISSIONS),
  CLIENT_ADMIN: Object.values(PERMISSIONS),

  CLIENT_IT_ADMIN: [
    PERMISSIONS.SEARCH_EXECUTE,
    PERMISSIONS.SEARCH_EXPORT,
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.CONFIG_UPLOAD,
    PERMISSIONS.CONFIG_CREATE,
    PERMISSIONS.CONFIG_VALIDATE,
    PERMISSIONS.SOURCE_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  PV_ADMINISTRATOR: [
    PERMISSIONS.SEARCH_EXECUTE,
    PERMISSIONS.SEARCH_EXPORT,
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.HITS_SUBMIT,
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.CONFIG_UPLOAD,
    PERMISSIONS.CONFIG_CREATE,
    PERMISSIONS.CONFIG_VALIDATE,
    PERMISSIONS.CONFIG_ACTIVATE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  SUPER_USER: [
    PERMISSIONS.SEARCH_EXECUTE,
    PERMISSIONS.SEARCH_EXPORT,
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.HITS_SUBMIT,
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.CONFIG_UPLOAD,
    PERMISSIONS.CONFIG_CREATE,
    PERMISSIONS.CONFIG_VALIDATE,
    PERMISSIONS.CONFIG_ACTIVATE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  QUALITY_APPROVER: [
    PERMISSIONS.SEARCH_EXECUTE,
    PERMISSIONS.SEARCH_EXPORT,
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.CONFIG_VALIDATE,
    PERMISSIONS.CONFIG_APPROVE,
    PERMISSIONS.CONFIG_ACTIVATE,
    PERMISSIONS.CONFIG_RETIRE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  QC_REVIEWER: [
    PERMISSIONS.SEARCH_EXECUTE,
    PERMISSIONS.SEARCH_EXPORT,
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.CONFIG_VALIDATE,
    PERMISSIONS.CONFIG_APPROVE,
    PERMISSIONS.CONFIG_ACTIVATE,
    PERMISSIONS.AUDIT_VIEW,
  ],

  LITERATURE_REVIEWER: [
    PERMISSIONS.SEARCH_EXECUTE,
    PERMISSIONS.SEARCH_EXPORT,
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.EVIDENCE_CREATE,
    PERMISSIONS.HITS_SUBMIT,
    PERMISSIONS.CONFIG_VIEW,
  ],

  AUDITOR: [
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.CONFIG_VIEW,
    PERMISSIONS.AUDIT_VIEW,
  ],

  READ_ONLY: [
    PERMISSIONS.SEARCH_EXECUTE,
    PERMISSIONS.SEARCH_HISTORY_VIEW,
    PERMISSIONS.CONFIG_VIEW,
  ],
};

export function roleHasPermission(
  roleKey: string,
  permission: Permission,
  customPermissions: readonly string[] = [],
): boolean {
  if (customPermissions.includes(permission)) return true;
  return (ROLE_PERMISSIONS[roleKey] || []).includes(permission);
}
