import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

/**
 * ClinixAI Nexus Platform - Package Workflow Details API
 * 
 * Fetches the unified manifest and operational state for a specific screening package.
 * Hardened with async route parameter constraints and path traversal defense protocols.
 */

export async function GET(
  request: NextRequest,
  props: { params: Promise<{ packageId: string }> }
) {
  try {
    // 1. Await the asynchronous route parameter promise to satisfy the compiler
    const { packageId } = await props.params;

    if (!packageId) {
      return NextResponse.json(
        { error: "Bad Request: Missing packageId validation token." },
        { status: 400 }
      );
    }

    // 2. Safely parse the tenant context out of the compound package ID
    // Expected structure format: "demo-tenant_PMID_12345678"
    const splitIndex = packageId.indexOf("_PMID_");
    let tenantId = "demo-tenant";
    let pmidValue = packageId;

    if (splitIndex !== -1) {
      tenantId = packageId.substring(0, splitIndex);
      pmidValue = packageId.substring(splitIndex + 1); // Yields "PMID_12345678"
    } else {
      pmidValue = packageId.startsWith("PMID_") ? packageId : `PMID_${packageId}`;
    }

    // 3. Resolve localized file system storage directories
    const projectRoot = process.cwd();
    const evidenceStoreRoot = path.resolve(projectRoot, "..", "evidence_store");
    
    // Target the core evidence manifest generated by the Python backend executor
    const manifestPath = path.join(evidenceStoreRoot, tenantId, pmidValue, "evidence_manifest.json");

    // 4. Hardened Security Layer: Prevent Directory Traversal Injections
    if (!manifestPath.startsWith(evidenceStoreRoot)) {
      return NextResponse.json(
        { error: "Security Violation: Unauthorized path operation attempted." },
        { status: 403 }
      );
    }

    // 5. Verify manifest presence on the storage volume
    if (!fs.existsSync(manifestPath)) {
      return NextResponse.json(
        { 
          error: "Not Found", 
          message: `Evidence package manifest for ID '${packageId}' could not be located.` 
        },
        { status: 404 }
      );
    }

    // 6. Read and serialize the localized package state payload
    const rawManifestData = fs.readFileSync(manifestPath, "utf-8");
    const manifestJson = JSON.parse(rawManifestData);

    // 7. Return the standardized structural manifest back to the UI state engine
    return NextResponse.json(manifestJson, {
      status: 200,
      headers: {
        "Cache-Control": "no-store, max-age=0",
      },
    });

  } catch (error: any) {
    console.error("[Nexus Package API Exception]:", error);
    return NextResponse.json(
      { error: "Internal Server Error: Failed to compile workflow package status map." },
      { status: 500 }
    );
  }
}